# Generated by Django 5.0.4 on 2024-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fibers', models.CharField(max_length=255, verbose_name='Тип прокладки кабеля')),
                ('count_fibers', models.IntegerField(verbose_name='Кол-во оптических волокон')),
                ('fading', models.FloatField(verbose_name='Километрическое затухание')),
                ('dispersion', models.FloatField(verbose_name='Допустимая дисперсия')),
                ('diameter', models.FloatField(verbose_name='Диаметр сердцевины волокна')),
            ],
        ),
    ]
