# Generated by Django 5.0.4 on 2024-05-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fibers', models.CharField(max_length=255, verbose_name='Название кабеля')),
                ('type_fibers', models.CharField(choices=[('в грунт', 'В грунт'), ('в каналах кабельной канализации', 'В каналах кабельной канализации'), ('Подвесной самонесущий', 'Подвесной самонесущий')], max_length=255, verbose_name='Тип прокладки кабеля')),
                ('count_fibers', models.IntegerField(verbose_name='Кол-во оптических волокон')),
                ('fading', models.FloatField(verbose_name='Километрическое затухание')),
                ('dispersion', models.FloatField(verbose_name='Допустимая дисперсия')),
                ('diameter', models.FloatField(verbose_name='Диаметр сердцевины волокна')),
            ],
            options={
                'verbose_name': 'Кабель',
                'verbose_name_plural': 'Кабели',
            },
        ),
        migrations.AlterModelOptions(
            name='inputdata',
            options={'verbose_name': 'Входные данные', 'verbose_name_plural': 'Входные данные'},
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='type_fibers',
            field=models.CharField(choices=[('в грунт', 'В грунт'), ('в каналах кабельной канализации', 'В каналах кабельной канализации'), ('Подвесной самонесущий', 'Подвесной самонесущий')], max_length=255, verbose_name='Тип прокладки кабеля'),
        ),
    ]
