# Generated by Django 5.0.4 on 2024-05-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fiberdata_alter_inputdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataMux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_fibers', models.IntegerField(verbose_name='Количество волокон')),
                ('count_canals', models.IntegerField(verbose_name='Количество каналов')),
                ('max_decay', models.FloatField(verbose_name='Максимальные вносимые затухания, дБ')),
            ],
            options={
                'verbose_name': 'мультиплексор',
                'verbose_name_plural': 'мультиплексоры',
            },
        ),
        migrations.AlterField(
            model_name='fiberdata',
            name='count_fibers',
            field=models.IntegerField(verbose_name='Кол-во ОВ в кабеле, до'),
        ),
        migrations.AlterField(
            model_name='fiberdata',
            name='diameter',
            field=models.FloatField(verbose_name='Коэффициент затухания, дБ/км, не более'),
        ),
        migrations.AlterField(
            model_name='fiberdata',
            name='dispersion',
            field=models.FloatField(verbose_name='Рабочая длина волны, нм'),
        ),
        migrations.AlterField(
            model_name='fiberdata',
            name='fading',
            field=models.FloatField(verbose_name='Диаметр кабеля, мм'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='count_fibers',
            field=models.IntegerField(verbose_name='Кол-во ОВ в кабеле, до'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='diameter',
            field=models.FloatField(verbose_name='Коэффициент затухания, дБ/км, не более'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='dispersion',
            field=models.FloatField(verbose_name='Рабочая длина волны, нм'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='fading',
            field=models.FloatField(verbose_name='Диаметр кабеля, мм'),
        ),
    ]
