# Generated by Django 5.0.4 on 2024-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inputdatamux_alter_fiberdata_count_fibers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название устройства')),
                ('count_fibers', models.IntegerField(verbose_name='Количество волокон')),
                ('count_canals', models.IntegerField(verbose_name='Количество каналов')),
                ('max_decay', models.FloatField(verbose_name='Максимальные вносимые затухания, дБ')),
            ],
            options={
                'verbose_name': 'мультиплексор',
                'verbose_name_plural': 'мультиплексоры',
            },
        ),
        migrations.AlterModelOptions(
            name='inputdata',
            options={'verbose_name': 'Входные данные кабель', 'verbose_name_plural': 'Входные данные кабель'},
        ),
        migrations.AlterModelOptions(
            name='inputdatamux',
            options={'verbose_name': 'Входные данные мультиплексор', 'verbose_name_plural': 'Входные данные мультиплексор'},
        ),
    ]
