# Generated by Django 5.0.4 on 2024-05-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_datamux_alter_inputdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_power', models.IntegerField(verbose_name='Выходная мощность, дБм')),
                ('gain_factor', models.FloatField(verbose_name='Коэффициент усиления, дБ')),
                ('noise_factor', models.FloatField(verbose_name='Коэффициент шума, дБ')),
            ],
            options={
                'verbose_name': 'Входные данные усилитель',
                'verbose_name_plural': 'Входные данные усилитель',
            },
        ),
        migrations.CreateModel(
            name='PowerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_power', models.CharField(max_length=255, verbose_name='Название устройства')),
                ('output_power', models.IntegerField(verbose_name='Выходная мощность, дБм')),
                ('gain_factor', models.FloatField(verbose_name='Коэффициент усиления, дБ')),
                ('noise_factor', models.FloatField(verbose_name='Коэффициент шума, дБ')),
            ],
            options={
                'verbose_name': 'Входные данные усилитель',
                'verbose_name_plural': 'Входные данные усилитель',
            },
        ),
    ]
